import React, { useState, useRef, useEffect, forwardRef, useImperativeHandle } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Send, Sparkles, User, Bot, Lightbulb, FileText, Image, BarChart3, Video, Copy, ThumbsUp, ThumbsDown, Maximize2, Minimize2 } from 'lucide-react';
import { Button } from '../ui/Button';
import ReactMarkdown from 'react-markdown';
import { AIContextSettings } from './AIContextSettings';
import { OpenAIService } from '../../lib/openai';

interface ChatMessage {
  id: string;
  type: 'user' | 'ai';
  content: string;
  timestamp: Date;
  suggestions?: string[];
  generatedContent?: {
    type: 'text' | 'image' | 'chart' | 'video';
    title: string;
    content: string;
  };
}

interface AIChatbotProps {
  projectId: string;
  aiSettings: AIContextSettings;
}

export interface AIChatbotRef {
  setInputValueFromOutside: (text: string) => void;
}

export const AIChatbot = forwardRef<AIChatbotRef, AIChatbotProps>(({ projectId, aiSettings }, ref) => {
  const [searchParams] = useSearchParams();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Expose methods to parent component
  useImperativeHandle(ref, () => ({
    setInputValueFromOutside: (text: string) => {
      setInputValue(text);
      inputRef.current?.focus();
    }
  }));

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Focus input on mount
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Check for auto-generation parameter and trigger content creation
  useEffect(() => {
    const autoGenerate = searchParams.get('autoGenerate');
    
    if (autoGenerate && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      
      // Add welcome message with AI context information
      const welcomeMessage: ChatMessage = {
        id: 'welcome',
        type: 'ai',
        content: generateContextualWelcomeMessage(autoGenerate),
        timestamp: new Date(),
        suggestions: [
          'Create additional content variations',
          'Generate social media posts for this',
          'Write email campaign about this topic',
          'Create supporting images'
        ]
      };
      
      setMessages([welcomeMessage]);
      
      // Automatically generate content based on the user's request
      setTimeout(() => {
        handleAutoGeneration(autoGenerate);
      }, 1000);
    } else if (!hasAutoGenerated) {
      // Default welcome message if no auto-generation
      const defaultWelcome: ChatMessage = {
        id: 'welcome',
        type: 'ai',
        content: generateContextualWelcomeMessage(),
        timestamp: new Date(),
        suggestions: [
          'Write a blog post about our product',
          'Create social media content',
          'Generate email marketing copy',
          'Design a marketing campaign'
        ]
      };
      
      setMessages([defaultWelcome]);
      setHasAutoGenerated(true);
    }
  }, [searchParams, hasAutoGenerated, aiSettings]);

  // Extract topic from user message
  const extractTopicFromMessage = (message: string): string => {
    const lowerMessage = message.toLowerCase();
    
    // Look for patterns like "blog post about X", "write about X", "article on X"
    const patterns = [
      /(?:blog post|article|post|write)\s+(?:about|on|regarding)\s+(.+)/i,
      /(?:create|generate|make)\s+(?:a|an)?\s*(?:blog post|article|post)\s+(?:about|on|regarding)\s+(.+)/i,
      /(?:blog|article|post)\s+(?:about|on|regarding)\s+(.+)/i
    ];
    
    for (const pattern of patterns) {
      const match = message.match(pattern);
      if (match && match[1]) {
        return match[1].trim();
      }
    }
    
    // If no specific pattern found, try to extract topic after common keywords
    const keywordPatterns = [
      /(?:about|on|regarding)\s+(.+)/i,
      /(?:topic|subject):\s*(.+)/i
    ];
    
    for (const pattern of keywordPatterns) {
      const match = message.match(pattern);
      if (match && match[1]) {
        return match[1].trim();
      }
    }
    
    // Default fallback
    return 'marketing strategies';
  };

  // Generate contextual welcome message based on AI settings
  const generateContextualWelcomeMessage = (userRequest?: string) => {
    let message = userRequest 
      ? `Hi! I'm your AI marketing assistant. I can see you want to work on: **"${userRequest}"**. Let me create that content for you right away!`
      : `Hi! I'm your AI marketing assistant. I'm here to help you create amazing content for your project. I can generate blog posts, social media content, marketing copy, images, and more!`;

    // Add persona-specific greeting
    if (aiSettings.persona && aiSettings.persona !== 'default') {
      switch (aiSettings.persona) {
        case 'seth_rogen':
          message = userRequest 
            ? `Hey there! Seth here. So you wanna work on "${userRequest}"? Dude, that's awesome! Let me whip up some content that's gonna be *chef's kiss* perfect. This is gonna be fun!`
            : `Hey! Seth Rogen here, ready to help you create some killer content! I'm like your creative buddy who happens to know a thing or two about marketing. Let's make some magic happen, eh?`;
          break;
        case 'alex_hormozi':
          message = userRequest 
            ? `Listen up. You want "${userRequest}"? Here's the deal - I'm going to create content that actually converts. No fluff, no BS, just results-driven material that makes you money. Let's get to work.`
            : `Alex Hormozi here. I don't do participation trophies. I create content that sells, converts, and builds real businesses. Tell me what you need and I'll give you the blueprint to dominate your market.`;
          break;
        case 'gary_vaynerchuk':
          message = userRequest 
            ? `YO! Gary V here and I'm PUMPED about "${userRequest}"! This is going to be FIRE! I'm about to create content that's going to absolutely CRUSH it for you. Let's GO GO GO!`
            : `What's up! Gary Vee in the house! I'm here to create content that's going to SMASH your competition! No excuses, no BS - just pure HUSTLE and results. What are we building today?`;
          break;
        case 'oprah_winfrey':
          message = userRequest 
            ? `Hello, beautiful soul! I'm so excited to help you with "${userRequest}". This is going to be a journey of discovery and empowerment. Let's create content that not only informs but truly transforms lives!`
            : `Welcome, dear friend! I'm here to help you create content that doesn't just reach people - it touches their hearts and changes their lives. Together, we'll craft messages that inspire and empower. What's calling to your heart today?`;
          break;
      }
    }

    // Add context information based on active settings
    const contextParts = [];
    
    if (aiSettings.brandVoiceId) {
      // Mock brand voice data - in real app, fetch from API
      const brandVoiceName = aiSettings.brandVoiceId === '1' ? 'Professional & Friendly' : 'Casual & Creative';
      contextParts.push(`I'll use your **"${brandVoiceName}"** brand voice`);
    }
    
    if (aiSettings.audienceId) {
      // Mock audience data - in real app, fetch from API
      const audienceName = aiSettings.audienceId === '1' ? 'Marketing Professionals' : 'Small Business Owners';
      contextParts.push(`target your **"${audienceName}"** audience`);
    }
    
    if (aiSettings.knowledgeIds.length > 0) {
      contextParts.push(`reference your ${aiSettings.knowledgeIds.length} knowledge sources`);
    }

    if (contextParts.length > 0 && aiSettings.persona === 'default') {
      message += `\n\n🎯 **Active Context:** I'll ${contextParts.join(', ')}.`;
    } else if (contextParts.length > 0) {
      // Persona-specific context messages
      switch (aiSettings.persona) {
        case 'seth_rogen':
          message += `\n\nOh, and I've got all your brand stuff loaded up - your voice, audience, the whole nine yards. This is gonna be so dialed in!`;
          break;
        case 'alex_hormozi':
          message += `\n\nI've analyzed your brand voice, audience data, and knowledge base. Everything I create will be laser-focused on your specific market.`;
          break;
        case 'gary_vaynerchuk':
          message += `\n\nI've got ALL your brand intel locked and loaded! Your voice, your audience, your knowledge - we're going to create content that's 100% YOU!`;
          break;
        case 'oprah_winfrey':
          message += `\n\nI've taken the time to understand your beautiful brand voice and the wonderful people you serve. Every word will be crafted with intention and love.`;
          break;
      }
    } else if (aiSettings.persona === 'default') {
      message += '\n\nSet up your brand voice and target audience in AI Context settings for more personalized content.';
    }

    // Add output format information
    if (aiSettings.outputFormat && aiSettings.persona === 'default') {
      const formatDescriptions = {
        casual: 'casual and conversational',
        professional: 'professional and formal',
        creative: 'creative and playful'
      };
      message += `\n\n📝 **Output Style:** ${formatDescriptions[aiSettings.outputFormat]} tone`;
    }

    // Add creativity level
    if (aiSettings.temperature !== undefined && aiSettings.persona === 'default') {
      const creativityLevel = aiSettings.temperature < 0.4 ? 'focused' : 
                             aiSettings.temperature > 0.7 ? 'creative' : 'balanced';
      message += ` with ${creativityLevel} creativity`;
    }

    if (aiSettings.persona === 'default') {
      message += `\n\n**What would you like to create today?**

💡 **Pro tip:** You can also highlight text in any content node and send it to me for rewriting!`;
    }

    return message;
  };

  // Auto-generation function with campaign detection
  const handleAutoGeneration = async (userRequest: string) => {
    setIsTyping(true);
    
    // Add user message
    const userMessage: ChatMessage = {
      id: `user_${Date.now()}`,
      type: 'user',
      content: userRequest,
      timestamp: new Date()
    };
    
    setMessages(prev => [...prev, userMessage]);
    
    // Check if this is a campaign request
    const isCampaign = userRequest.toLowerCase().includes('campaign') || 
                       userRequest.toLowerCase().includes('launch') ||
                       userRequest.toLowerCase().includes('promote');
    
    if (isCampaign) {
      // Generate complete campaign assets
      const campaignAssets = [
        {
          type: 'social_ad',
          title: '📱 Facebook & Instagram Ads',
          content: 'Eye-catching visuals with compelling copy for social media advertising'
        },
        {
          type: 'text',
          title: '📧 Email Welcome Series',
          content: 'Day 1: Welcome\nDay 3: Value Proposition\nDay 7: Special Offer'
        },
        {
          type: 'text',
          title: '📝 Blog Post',
          content: 'In-depth content establishing thought leadership'
        },
        {
          type: 'text',
          title: '🎯 Landing Page',
          content: 'High-converting landing page with clear CTA'
        },
        {
          type: 'text',
          title: '🔄 Follow-up Email',
          content: 'Post-purchase email sequence for customer retention'
        }
      ];

      // Add all campaign assets to canvas with staggered timing
      campaignAssets.forEach((asset, index) => {
        setTimeout(() => {
          if ((window as any).addCanvasItem) {
            (window as any).addCanvasItem(
              asset.type,
              asset.content,
              asset.title
            );
          }
        }, 500 + (index * 300)); // Stagger creation
      });

      // Generate AI response for campaign using OpenAI
      try {
        const aiContent = await OpenAIService.generateCampaignContent(userRequest, aiSettings);
        
        const aiResponse: ChatMessage = {
          id: `ai_${Date.now()}`,
          type: 'ai',
          content: aiContent,
          timestamp: new Date(),
          suggestions: [
            'Organize into Journey View',
            'Create additional variations',
            'Generate supporting content',
            'Add performance metrics'
          ]
        };
        
        setMessages(prev => [...prev, aiResponse]);
        
        // Show success message
        setTimeout(() => {
          const successMessage: ChatMessage = {
            id: `ai_success_${Date.now()}`,
            type: 'ai',
            content: generatePersonaSuccessMessage(),
            timestamp: new Date(),
            suggestions: [
              'Organize into Journey View',
              'Create additional variations',
              'Generate supporting content',
              'Add performance metrics'
            ]
          };
          setMessages(prev => [...prev, successMessage]);
        }, 2000);
        
      } catch (error) {
        console.error('Error generating campaign response:', error);
        // Fallback to mock response if OpenAI fails
        const fallbackResponse: ChatMessage = {
          id: `ai_${Date.now()}`,
          type: 'ai',
          content: generatePersonaSuccessMessage(),
          timestamp: new Date(),
          suggestions: [
            'Organize into Journey View',
            'Create additional variations',
            'Generate supporting content',
            'Add performance metrics'
          ]
        };
        setMessages(prev => [...prev, fallbackResponse]);
      } finally {
        setIsTyping(false);
      }
    } else {
      // Generate AI response based on the request
      try {
        const aiResponse = await generateAIResponse(userRequest);
        setMessages(prev => [...prev, aiResponse]);
        
        // Add content to canvas if generated
        if (aiResponse.generatedContent && (window as any).addCanvasItem) {
          (window as any).addCanvasItem(
            aiResponse.generatedContent.type,
            aiResponse.generatedContent.content,
            aiResponse.generatedContent.title
          );
        }
      } catch (error) {
        console.error('Error generating AI response:', error);
      } finally {
        setIsTyping(false);
      }
    }
  };

  // Generate persona-specific success message
  const generatePersonaSuccessMessage = () => {
    switch (aiSettings.persona) {
      case 'seth_rogen':
        return `🚀 Boom! Complete campaign created! That was like... *chef's kiss* beautiful, man! Now click that "✨ Journey View" button to see how it all flows together. It's gonna look so good!`;
      case 'alex_hormozi':
        return `🚀 Done. Complete campaign system deployed. Every piece is designed to move prospects through your funnel and convert. Click "✨ Journey View" to see the money-making machine we just built.`;
      case 'gary_vaynerchuk':
        return `🚀 BOOM! We just created a COMPLETE campaign that's going to CRUSH IT! This is FIRE! Hit that "✨ Journey View" button and watch your customer journey come to LIFE!`;
      case 'oprah_winfrey':
        return `🚀 Beautiful! We've created a complete campaign that will touch hearts and transform lives! Click "✨ Journey View" to see how each piece works together to create a meaningful customer experience.`;
      default:
        return `🚀 Complete campaign created! Click "✨ Journey View" button to see the flow!`;
    }
  };

  // Enhanced AI response generation using OpenAI
  const generateAIResponse = async (userMessage: string): Promise<ChatMessage> => {
    const messageId = `ai_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    try {
      // Get ACTUAL AI response from OpenAI
      const aiContent = await OpenAIService.generateMarketingContent(userMessage, aiSettings);
      
      // Detect what type of content was requested and determine if it should be added to canvas
      const lowerMessage = userMessage.toLowerCase();
      let generatedContent = undefined;
      
      // Check if this is content that should be added to canvas
      const shouldAddToCanvas = lowerMessage.includes('write') || 
                               lowerMessage.includes('create') || 
                               lowerMessage.includes('generate') ||
                               lowerMessage.includes('landing page') || 
                               lowerMessage.includes('email') || 
                               lowerMessage.includes('social media') ||
                               lowerMessage.includes('blog') ||
                               lowerMessage.includes('copy') ||
                               lowerMessage.includes('content') ||
                               lowerMessage.includes('post') ||
                               lowerMessage.includes('campaign') ||
                               lowerMessage.includes('ad');
      
      if (shouldAddToCanvas) {
        // Create a more descriptive title based on the request
        let title = `📝 ${userMessage.slice(0, 50)}`;
        if (userMessage.length > 50) title += '...';
        
        // Determine content type based on request
        let contentType: 'text' | 'image' | 'chart' | 'video' = 'text';
        if (lowerMessage.includes('image') || lowerMessage.includes('visual')) {
          contentType = 'image';
        } else if (lowerMessage.includes('chart') || lowerMessage.includes('graph')) {
          contentType = 'chart';
        } else if (lowerMessage.includes('video')) {
          contentType = 'video';
        }
        
        generatedContent = {
          type: contentType,
          title: title,
          content: aiContent
        };
      }

      return {
        id: messageId,
        type: 'ai',
        content: aiContent, // Use the ACTUAL AI response
        timestamp: new Date(),
        generatedContent,
        suggestions: [
          'Make it more persuasive',
          'Create A/B test variation',
          'Adapt for social media',
          'Generate email version'
        ]
      };
      
    } catch (error) {
      console.error('Error generating AI response:', error);
      
      // Fallback to mock response if OpenAI fails
      return generateMockAIResponse(userMessage);
    }
  };

  // Fallback mock response function
  const generateMockAIResponse = (userMessage: string): ChatMessage => {
    const messageId = `ai_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    // Determine response type based on user input
    const lowerMessage = userMessage.toLowerCase();
    
    // Check if this is a rewrite request
    if (lowerMessage.includes('rewrite') || lowerMessage.includes('please rewrite this text:')) {
      const textToRewrite = userMessage.replace(/please rewrite this text:\s*["']?/i, '').replace(/["']?$/, '');
      
      return {
        id: messageId,
        type: 'ai',
        content: generateContextualRewrite(textToRewrite),
        timestamp: new Date(),
        suggestions: [
          'Make it more casual',
          'Make it more professional', 
          'Make it shorter',
          'Add more detail'
        ]
      };
    }
    
    // Check for blog post requests and extract topic
    if (lowerMessage.includes('blog') || lowerMessage.includes('article') || lowerMessage.includes('post')) {
      const topic = extractTopicFromMessage(userMessage);
      
      return {
        id: messageId,
        type: 'ai',
        content: generateContextualBlogResponse(topic),
        timestamp: new Date(),
        generatedContent: {
          type: 'text',
          title: generateBlogTitle(topic),
          content: generateContextualBlogContent(topic)
        },
        suggestions: [
          'Create social media posts for this blog',
          `Generate email campaign about ${topic}`,
          `Design infographic about ${topic}`,
          'Write a follow-up article'
        ]
      };
    }
    
    // Default response for any other request
    return {
      id: messageId,
      type: 'ai',
      content: generateContextualDefaultResponse(userMessage),
      timestamp: new Date(),
      suggestions: [
        'Write a blog post',
        'Create social media content',
        'Generate email campaign',
        'Design marketing visuals'
      ]
    };
  };

  // Generate blog title based on topic
  const generateBlogTitle = (topic: string): string => {
    const titleTemplates = [
      `The Ultimate Guide to ${topic}`,
      `Everything You Need to Know About ${topic}`,
      `${topic}: A Comprehensive Guide`,
      `Mastering ${topic}: Tips and Strategies`,
      `The Complete ${topic} Handbook`,
      `${topic} Made Simple: A Step-by-Step Guide`
    ];
    
    // Capitalize first letter of topic
    const capitalizedTopic = topic.charAt(0).toUpperCase() + topic.slice(1);
    
    // Select a random template and replace topic
    const randomTemplate = titleTemplates[Math.floor(Math.random() * titleTemplates.length)];
    return randomTemplate.replace(topic, capitalizedTopic);
  };

  // Generate contextual rewrite based on AI settings
  const generateContextualRewrite = (originalText: string) => {
    let rewrittenText = originalText;
    
    // Apply persona-specific rewriting
    if (aiSettings.persona) {
      switch (aiSettings.persona) {
        case 'seth_rogen':
          rewrittenText = originalText.replace(/\b(very)\b/g, 'super')
                                     .replace(/\b(excellent)\b/g, 'awesome')
                                     .replace(/\./g, ', eh?')
                                     .replace(/!/g, ', dude!');
          break;
        case 'alex_hormozi':
          rewrittenText = originalText.replace(/\b(good)\b/g, 'profitable')
                                     .replace(/\b(nice)\b/g, 'effective')
                                     .replace(/\b(great)\b/g, 'game-changing');
          break;
        case 'gary_vaynerchuk':
          rewrittenText = originalText.replace(/\b(good)\b/g, 'AMAZING')
                                     .replace(/\b(nice)\b/g, 'INCREDIBLE')
                                     .replace(/\./g, '!')
                                     .toUpperCase();
          break;
        case 'oprah_winfrey':
          rewrittenText = originalText.replace(/\b(good)\b/g, 'beautiful')
                                     .replace(/\b(nice)\b/g, 'wonderful')
                                     .replace(/\b(great)\b/g, 'magnificent');
          break;
        default:
          // Apply tone based on output format
          if (aiSettings.outputFormat === 'casual') {
            rewrittenText = originalText.replace(/\b(utilize|implement|facilitate)\b/g, 'use')
                                       .replace(/\b(commence|initiate)\b/g, 'start')
                                       .replace(/\./g, '!')
                                       .replace(/\b(very)\b/g, 'super');
          } else if (aiSettings.outputFormat === 'professional') {
            rewrittenText = originalText.replace(/\b(use)\b/g, 'utilize')
                                       .replace(/\b(start)\b/g, 'commence')
                                       .replace(/!/g, '.');
          } else if (aiSettings.outputFormat === 'creative') {
            rewrittenText = originalText.replace(/\b(good)\b/g, 'amazing')
                                       .replace(/\b(nice)\b/g, 'fantastic')
                                       .replace(/\b(big)\b/g, 'massive');
          }
      }
    }

    const personaNote = aiSettings.persona && aiSettings.persona !== 'default' 
      ? `in ${aiSettings.persona.replace('_', ' ')} style` 
      : `using your **${aiSettings.outputFormat}** tone and **${aiSettings.temperature < 0.4 ? 'focused' : aiSettings.temperature > 0.7 ? 'creative' : 'balanced'}** creativity level`;

    return `I've rewritten the selected text ${personaNote}!

**Original text:** "${originalText}"

**Rewritten version:** "${rewrittenText}"

${aiSettings.brandVoiceId ? 'This version aligns with your selected brand voice and ' : ''}maintains the original meaning while enhancing ${aiSettings.outputFormat === 'casual' ? 'approachability and friendliness' : aiSettings.outputFormat === 'professional' ? 'authority and credibility' : 'creativity and engagement'}.

Would you like me to try a different approach or style?`;
  };

  // Generate contextual blog response
  const generateContextualBlogResponse = (topic: string) => {
    const brandVoiceNote = aiSettings.brandVoiceId ? 'using your selected brand voice and ' : '';
    const audienceNote = aiSettings.audienceId ? 'tailored for your target audience' : 'optimized for engagement';
    const knowledgeNote = aiSettings.knowledgeIds.length > 0 ? ` I've incorporated insights from your ${aiSettings.knowledgeIds.length} knowledge sources.` : '';
    
    let response = `Perfect! I've created a comprehensive blog post about **${topic}** ${brandVoiceNote}${audienceNote}.${knowledgeNote}`;

    // Add persona-specific response
    if (aiSettings.persona && aiSettings.persona !== 'default') {
      switch (aiSettings.persona) {
        case 'seth_rogen':
          response = `Dude, this blog post about **${topic}** is gonna be so good! I made it super engaging and fun to read. Your audience is gonna love it!`;
          break;
        case 'alex_hormozi':
          response = `Blog post about **${topic}** is done. Every word is designed to educate, build authority, and drive action. This will position you as the expert in your space.`;
          break;
        case 'gary_vaynerchuk':
          response = `YES! Just created an INCREDIBLE blog post about **${topic}** that's going to absolutely CRUSH it! This content is going to build your brand and drive MASSIVE engagement!`;
          break;
        case 'oprah_winfrey':
          response = `I've lovingly crafted a beautiful blog post about **${topic}** that will inspire and empower your readers. Every word is chosen to uplift and transform lives.`;
          break;
      }
    }

    response += `

**Key features of your blog post:**
- ${aiSettings.outputFormat === 'professional' ? 'Professional and authoritative' : aiSettings.outputFormat === 'casual' ? 'Conversational and approachable' : 'Creative and engaging'} tone
- SEO-optimized structure focused on "${topic}"
- ${aiSettings.temperature > 0.7 ? 'Creative and unique' : aiSettings.temperature < 0.4 ? 'Focused and precise' : 'Balanced and practical'} insights
- Reader-friendly formatting

The content has been added to your canvas where you can further edit and customize it. You can double-click the content node to edit it directly, or highlight specific sections and send them back to me for rewriting!`;

    return response;
  };

  // Generate contextual blog content based on topic
  const generateContextualBlogContent = (topic: string) => {
    const title = generateBlogTitle(topic);
    const capitalizedTopic = topic.charAt(0).toUpperCase() + topic.slice(1);
    
    let baseContent = `# ${title}

${capitalizedTopic} has become increasingly important in today's rapidly evolving landscape. Whether you're a beginner looking to understand the fundamentals or an expert seeking advanced strategies, this comprehensive guide will provide you with valuable insights and actionable advice.

## Understanding ${capitalizedTopic}

${capitalizedTopic} encompasses various aspects that are crucial for success. Let's explore the key components that make up this important topic.

### Why ${capitalizedTopic} Matters

In today's competitive environment, understanding ${topic} is essential for:
- Achieving better results
- Staying ahead of the competition
- Making informed decisions
- Maximizing efficiency and effectiveness

## Key Strategies for ${capitalizedTopic}

### 1. Foundation Building
Start with a solid understanding of the fundamentals. This includes:
- Learning the basic principles
- Understanding common terminology
- Identifying key stakeholders
- Setting clear objectives

### 2. Implementation Best Practices
When implementing ${topic} strategies:
- Start with small, manageable steps
- Monitor progress regularly
- Adjust your approach based on results
- Seek feedback from experts and peers

### 3. Advanced Techniques
Once you've mastered the basics, consider these advanced approaches:
- Leveraging technology and automation
- Implementing data-driven decision making
- Building strategic partnerships
- Continuous improvement processes

## Common Challenges and Solutions

### Challenge 1: Getting Started
Many people struggle with where to begin. The solution is to:
- Break down the topic into smaller, manageable pieces
- Set realistic goals and timelines
- Seek guidance from experienced professionals
- Start with proven methods before experimenting

### Challenge 2: Staying Current
${capitalizedTopic} is constantly evolving. To stay current:
- Follow industry leaders and publications
- Attend conferences and workshops
- Join professional communities
- Regularly review and update your strategies

## Measuring Success

To ensure your ${topic} efforts are effective, track these key metrics:
- Performance indicators relevant to your goals
- Return on investment (ROI)
- User satisfaction and feedback
- Long-term sustainability

## Future Trends in ${capitalizedTopic}

Looking ahead, several trends are shaping the future of ${topic}:
- Increased automation and AI integration
- Greater focus on personalization
- Enhanced data analytics capabilities
- Improved user experience design

## Conclusion

${capitalizedTopic} is a multifaceted topic that requires careful planning, consistent execution, and continuous learning. By following the strategies outlined in this guide, you'll be well-equipped to achieve success in your ${topic} endeavors.

Remember that mastery takes time, so be patient with yourself as you develop your skills. Stay curious, keep learning, and don't hesitate to seek help when needed.

---

*Ready to take your ${topic} to the next level? Start implementing these strategies today and watch your results improve!*`;

    // Modify content based on persona
    if (aiSettings.persona) {
      switch (aiSettings.persona) {
        case 'seth_rogen':
          baseContent = baseContent
            .replace(/encompasses various aspects/g, 'covers lots of different things')
            .replace(/crucial for success/g, 'super important for winning')
            .replace(/fundamental principles/g, 'basic stuff you need to know')
            .replace(/implementing/g, 'putting into action')
            .replace(/leveraging/g, 'using')
            .replace(/multifaceted topic/g, 'topic with many sides');
          break;
        case 'alex_hormozi':
          baseContent = baseContent
            .replace(/has become increasingly important/g, 'directly impacts your bottom line')
            .replace(/comprehensive guide/g, 'profit-focused blueprint')
            .replace(/valuable insights/g, 'money-making strategies')
            .replace(/actionable advice/g, 'proven tactics that work')
            .replace(/competitive environment/g, 'marketplace where winners take all');
          break;
        case 'gary_vaynerchuk':
          baseContent = baseContent
            .replace(/has become increasingly important/g, 'has emerged as a game-changing force')
            .replace(/comprehensive guide/g, 'ultimate roadmap to SUCCESS')
            .replace(/valuable insights/g, 'GOLDEN nuggets of wisdom')
            .replace(/actionable advice/g, 'power-packed strategies')
            .replace(/competitive environment/g, 'battlefield of HUSTLE and GRIND');
          break;
        case 'oprah_winfrey':
          baseContent = baseContent
            .replace(/has become increasingly important/g, 'has emerged as a beautiful opportunity for growth')
            .replace(/comprehensive guide/g, 'loving guide to transformation')
            .replace(/valuable insights/g, 'precious wisdom')
            .replace(/actionable advice/g, 'empowering guidance')
            .replace(/competitive environment/g, 'world where we can all shine together');
          break;
      }
    } else if (aiSettings.outputFormat === 'casual') {
      baseContent = baseContent
        .replace(/encompasses various aspects/g, 'covers lots of different things')
        .replace(/crucial for success/g, 'super important for winning')
        .replace(/fundamental principles/g, 'basic stuff you need to know')
        .replace(/implementing/g, 'putting into action')
        .replace(/leveraging/g, 'using')
        .replace(/multifaceted topic/g, 'topic with many sides');
    } else if (aiSettings.outputFormat === 'creative') {
      baseContent = baseContent
        .replace(/has become increasingly important/g, 'has emerged as a game-changing force')
        .replace(/comprehensive guide/g, 'ultimate roadmap to success')
        .replace(/valuable insights/g, 'golden nuggets of wisdom')
        .replace(/actionable advice/g, 'power-packed strategies')
        .replace(/competitive environment/g, 'battlefield of innovation');
    }

    return baseContent;
  };

  // Generate contextual default response
  const generateContextualDefaultResponse = (userMessage: string) => {
    const contextInfo = [];
    
    if (aiSettings.brandVoiceId) {
      contextInfo.push('your selected brand voice');
    }
    if (aiSettings.audienceId) {
      contextInfo.push('your target audience preferences');
    }
    if (aiSettings.knowledgeIds.length > 0) {
      contextInfo.push(`insights from your ${aiSettings.knowledgeIds.length} knowledge sources`);
    }

    const contextText = contextInfo.length > 0 
      ? ` I'll incorporate ${contextInfo.join(', ')} to ensure the content aligns perfectly with your brand and goals.`
      : '';

    let response = `I understand you'd like help with **"${userMessage}"**. I can assist you with creating various types of marketing content including:

• **Blog posts and articles** - SEO-optimized, engaging content in ${aiSettings.outputFormat || 'professional'} tone
• **Social media content** - Posts, captions, and hashtags  
• **Email campaigns** - Subject lines, sequences, and newsletters
• **Marketing copy** - Landing pages, ads, and sales materials
• **Visual concepts** - Image ideas and design briefs
• **Video scripts** - YouTube, TikTok, and promotional videos

${contextText}

**💡 Pro tip:** You can also highlight text in any content node on the canvas and send it to me for rewriting or improvement!

What specific type of content would you like me to create for your project?`;

    // Add persona-specific response
    if (aiSettings.persona && aiSettings.persona !== 'default') {
      switch (aiSettings.persona) {
        case 'seth_rogen':
          response = `Oh cool, you want help with **"${userMessage}"**! I'm totally down to help you create some awesome content. I can make blog posts, social stuff, emails - whatever you need, man! Just tell me what you're thinking and I'll make it happen!`;
          break;
        case 'alex_hormozi':
          response = `You want **"${userMessage}"**? Here's what I can build for you: High-converting sales copy, email sequences that actually sell, content that positions you as the authority, and marketing materials that drive revenue. What's the goal?`;
          break;
        case 'gary_vaynerchuk':
          response = `YES! **"${userMessage}"** - I LOVE IT! I can create CRUSHING content for you - blogs that BUILD your brand, social posts that get ENGAGEMENT, emails that CONVERT! What are we building today? Let's GO!`;
          break;
        case 'oprah_winfrey':
          response = `Beautiful! You want to work on **"${userMessage}"** - I'm so excited to help you create content that will touch hearts and inspire action. Whether it's blog posts that empower, social content that uplifts, or emails that connect - let's create something meaningful together!`;
          break;
      }
    }

    return response;
  };

  // Handle sending message
  const handleSendMessage = async () => {
    if (!inputValue.trim()) return;

    const userMessage: ChatMessage = {
      id: `user_${Date.now()}`,
      type: 'user',
      content: inputValue,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsTyping(true);

    try {
      const aiResponse = await generateAIResponse(inputValue);
      setMessages(prev => [...prev, aiResponse]);
      
      // FIXED: Add content to canvas immediately after generating the response
      if (aiResponse.generatedContent && (window as any).addCanvasItem) {
        // Add a small delay to ensure the message is rendered first
        setTimeout(() => {
          (window as any).addCanvasItem(
            aiResponse.generatedContent!.type,
            aiResponse.generatedContent!.content,
            aiResponse.generatedContent!.title
          );
        }, 100);
      }
    } catch (error) {
      console.error('Error generating AI response:', error);
    } finally {
      setIsTyping(false);
    }
  };

  // Handle suggestion click
  const handleSuggestionClick = (suggestion: string) => {
    setInputValue(suggestion);
    inputRef.current?.focus();
  };

  // Handle key press
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  // Copy content to clipboard
  const copyToClipboard = (content: string) => {
    navigator.clipboard.writeText(content);
  };

  return (
    <div className={`bg-white border-l border-gray-200 flex flex-col transition-all duration-300 ${
      isExpanded ? 'w-[600px]' : 'w-96'
    }`}>
      {/* Chat Header */}
      <div className="p-6 border-b border-gray-200 bg-gradient-to-r from-indigo-50 to-purple-50">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">
                {aiSettings.persona && aiSettings.persona !== 'default' 
                  ? aiSettings.persona.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())
                  : 'AI Assistant'
                }
              </h3>
              <p className="text-sm text-gray-600">
                {aiSettings.brandVoiceId || aiSettings.audienceId || aiSettings.knowledgeIds.length > 0
                  ? 'Context-aware marketing co-pilot'
                  : 'Your marketing co-pilot'
                }
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {/* Context Indicators */}
            {(aiSettings.brandVoiceId || aiSettings.audienceId || aiSettings.knowledgeIds.length > 0 || (aiSettings.persona && aiSettings.persona !== 'default')) && (
              <div className="flex items-center gap-1">
                {aiSettings.brandVoiceId && <div className="w-2 h-2 bg-blue-500 rounded-full" title="Brand Voice Active" />}
                {aiSettings.audienceId && <div className="w-2 h-2 bg-green-500 rounded-full" title="Audience Active" />}
                {aiSettings.knowledgeIds.length > 0 && <div className="w-2 h-2 bg-purple-500 rounded-full" title="Knowledge Base Active" />}
                {aiSettings.persona && aiSettings.persona !== 'default' && <div className="w-2 h-2 bg-orange-500 rounded-full" title="Persona Active" />}
              </div>
            )}
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setIsExpanded(!isExpanded)}
              className="p-2"
            >
              {isExpanded ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
            </Button>
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
        {messages.map((message) => (
          <div key={message.id} className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[85%] ${message.type === 'user' ? 'order-2' : 'order-1'}`}>
              {/* Avatar */}
              <div className={`flex items-center gap-3 mb-3 ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                  message.type === 'user' 
                    ? 'bg-gray-200 order-2' 
                    : 'bg-gradient-to-br from-indigo-500 to-purple-600 order-1'
                }`}>
                  {message.type === 'user' ? (
                    <User size={16} className="text-gray-600" />
                  ) : (
                    <Bot size={16} className="text-white" />
                  )}
                </div>
                <span className="text-xs text-gray-500 font-medium">
                  {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>

              {/* Message Content */}
              <div className={`rounded-2xl p-4 ${
                message.type === 'user'
                  ? 'bg-indigo-600 text-white'
                  : 'bg-gray-100 text-gray-900'
              }`}>
                <div className="text-sm leading-relaxed">
                  {message.type === 'ai' ? (
                    <ReactMarkdown className="prose prose-sm max-w-none">
                      {message.content}
                    </ReactMarkdown>
                  ) : (
                    <div className="whitespace-pre-wrap">{message.content}</div>
                  )}
                </div>

                {/* Generated Content */}
                {message.generatedContent && (
                  <div className="mt-4 p-4 bg-white rounded-xl border border-gray-200 shadow-sm">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-2">
                        {message.generatedContent.type === 'text' && <FileText size={16} className="text-blue-600" />}
                        {message.generatedContent.type === 'image' && <Image size={16} className="text-green-600" />}
                        {message.generatedContent.type === 'chart' && <BarChart3 size={16} className="text-purple-600" />}
                        {message.generatedContent.type === 'video' && <Video size={16} className="text-orange-600" />}
                        <span className="text-sm font-semibold text-gray-900">
                          {message.generatedContent.title}
                        </span>
                      </div>
                      <button
                        onClick={() => copyToClipboard(message.generatedContent!.content)}
                        className="p-1.5 text-gray-400 hover:text-gray-600 rounded-lg hover:bg-gray-100 transition-colors"
                        title="Copy to clipboard"
                      >
                        <Copy size={14} />
                      </button>
                    </div>
                    <div className="text-xs text-gray-600 bg-gray-50 p-3 rounded-lg max-h-32 overflow-y-auto">
                      {message.generatedContent.content.length > 200 
                        ? `${message.generatedContent.content.substring(0, 200)}...`
                        : message.generatedContent.content
                      }
                    </div>
                    <div className="flex items-center gap-3 mt-3">
                      <div className="flex items-center gap-1 text-xs text-green-600 bg-green-50 px-2 py-1 rounded-full">
                        <span>✓</span>
                        <span>Added to Canvas</span>
                      </div>
                      <button className="p-1 text-gray-400 hover:text-green-600 transition-colors">
                        <ThumbsUp size={12} />
                      </button>
                      <button className="p-1 text-gray-400 hover:text-red-600 transition-colors">
                        <ThumbsDown size={12} />
                      </button>
                    </div>
                  </div>
                )}

                {/* Suggestions */}
                {message.suggestions && (
                  <div className="mt-4 space-y-2">
                    {message.suggestions.map((suggestion, index) => (
                      <button
                        key={index}
                        onClick={() => handleSuggestionClick(suggestion)}
                        className="block w-full text-left p-3 text-xs bg-white/10 hover:bg-white/20 rounded-xl border border-white/20 transition-colors"
                      >
                        <div className="flex items-center gap-2">
                          <Lightbulb size={12} className="text-yellow-400" />
                          <span>{suggestion}</span>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}

        {/* Typing Indicator */}
        {isTyping && (
          <div className="flex justify-start">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center">
                <Bot size={16} className="text-white" />
              </div>
              <div className="bg-gray-100 rounded-2xl p-4">
                <div className="flex space-x-1">
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                </div>
              </div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-6 border-t border-gray-200 bg-gray-50">
        <div className="flex gap-3">
          <input
            ref={inputRef}
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Ask me to create marketing content..."
            className="flex-1 px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-sm bg-white"
            disabled={isTyping}
          />
          <Button
            onClick={handleSendMessage}
            disabled={!inputValue.trim() || isTyping}
            size="sm"
            className="px-4 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 rounded-xl"
          >
            <Send size={16} />
          </Button>
        </div>
        <div className="flex items-center justify-between mt-3">
          <p className="text-xs text-gray-500">
            {import.meta.env.VITE_OPENAI_API_KEY ? 'Powered by OpenAI GPT' : 'AI can make mistakes. Verify important information.'}
          </p>
          {/* Context Status */}
          {(aiSettings.brandVoiceId || aiSettings.audienceId || aiSettings.knowledgeIds.length > 0 || (aiSettings.persona && aiSettings.persona !== 'default')) && (
            <div className="flex items-center gap-1 text-xs text-indigo-600">
              <Sparkles size={12} />
              <span>Context Active</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
});

AIChatbot.displayName = 'AIChatbot';